# Headless Service for internal network
apiVersion: v1
kind: Service
metadata:
  name: automata
  labels:
    app: automata
spec:
  ports:
  - name: p2p
    protocol: TCP
    port: 30333
    targetPort: 30333
  - name: websocket
    protocol: TCP
    port: 9944
    targetPort: 9944
  - name: http
    protocol: TCP
    port: 9933
    targetPort: 9933
  clusterIP: None
  selector:
    app: automata