apiVersion: v1
kind: Service
metadata:
  name: automata-0
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: automata-0
  ports:
  - name: websocket
    protocol: TCP
    port: 9944
    targetPort: 9944
  - name: http
    protocol: TCP
    port: 9933
    targetPort: 9933
  - name: p2p
    protocol: TCP
    port: 30333
    targetPort: 30333

---
apiVersion: v1
kind: Service
metadata:
  name: automata-1
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: automata-1
  ports:
  - name: websocket
    protocol: TCP
    port: 9944
    targetPort: 9944
  - name: http
    protocol: TCP
    port: 9933
    targetPort: 9933
  - name: p2p
    protocol: TCP
    port: 30333
    targetPort: 30333