apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: automata
spec:
  selector:
    matchLabels:
      app: automata
  serviceName: "automata"
  replicas: 2
  template:
    metadata:
      labels:
        app: automata
    spec:
      securityContext:
        runAsUser: 1000 
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: automata
        image: atactr/automata:contextfree-v0.1.0-rc4
        args: ["--node-type", "archive", "--name", "alice"]
        ports:
        - containerPort: 30333
        - containerPort: 9944
        - containerPort: 9933
        volumeMounts:
        - name: automata-store
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: automata-store
    spec:
      accessModes: 
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
